using System.Text;

namespace RecompOne.Recompiler.CodeGen;

//"splitProjects": every image gets its own class library, so compiling the port never needs all of the generated
//code in one compilation (a game with a dozen overlays is well over 100 MB of C#, which one csc process cannot hold
//on an ordinary PC). Layout under the output folder:
//  Common/Recompiled.Common.csproj   Stubs.cs + the port's patches/ folder, referenced by every image
//  <image>/Recompiled.<image>.csproj  one image's code and dispatch table
//  Entry/Recompiled.Entry.csproj      Entry.cs (registers every image and starts the game), references them all
//The port's executable loads Recompiled.Entry at startup, so it can be built once without any generated code and
//the libraries compiled later (by the port's own project, or by a tool on the player's PC).
//Dependencies only go overlay -> main -> Common, see OverlayWriter.CallTargetsFor.
public sealed class ProjectLayoutWriter
{
    public const string CommonName = "Common";
    public const string EntryName = "Entry";

    private readonly string _outDir;
    private readonly string? _runtimeProject;
    private readonly HashSet<string> _images = new(StringComparer.OrdinalIgnoreCase);

    //runtimeProject null: sources only, no project files are written
    public ProjectLayoutWriter(string outDir, string? runtimeProject)
    {
        _outDir = Path.GetFullPath(outDir);
        _runtimeProject = runtimeProject == null ? null : Path.GetFullPath(runtimeProject);
        if (_runtimeProject != null && !File.Exists(_runtimeProject))
            throw new FileNotFoundException($"runtimeProject not found: {_runtimeProject}");

        Directory.CreateDirectory(CommonDir);

        //the monolithic layout wrote every image (and Entry.cs) straight into the output folder, those would be stale
        foreach (var f in Directory.GetFiles(_outDir, "*.cs"))
            File.Delete(f);
    }

    public string CommonDir => Path.Combine(_outDir, CommonName);

    public string EntryDir
    {
        get
        {
            var dir = Path.Combine(_outDir, EntryName);
            Directory.CreateDirectory(dir);
            return dir;
        }
    }

    public string ImageDir(string image)
    {
        var dir = Path.Combine(_outDir, image);
        Directory.CreateDirectory(dir);
        return dir;
    }

    public static string ProjectName(string image) => $"Recompiled.{image}";

    public void WriteImageProject(string image, string? resident)
    {
        _images.Add(image);
        var dir = ImageDir(image);
        var refs = new List<string> { _runtimeProject!, Path.Combine(CommonDir, $"{ProjectName(CommonName)}.csproj") };
        if (resident != null) refs.Add(Path.Combine(_outDir, resident, $"{ProjectName(resident)}.csproj"));
        WriteProject(dir, ProjectName(image), refs, []);
    }

    public void WriteCommonProject()
    {
        //the port's hand written patches are called by generated code (config "patches"), so they are compiled with it
        var patches = Path.GetFullPath(Path.Combine(_outDir, "..", "patches"));
        if (_runtimeProject == null && Directory.Exists(patches))
        {
            var copy = Path.Combine(CommonDir, "patches");
            foreach (var src in Directory.GetFiles(patches, "*.cs", SearchOption.AllDirectories))
            {
                var dst = Path.Combine(copy, Path.GetRelativePath(patches, src));
                Directory.CreateDirectory(Path.GetDirectoryName(dst)!);
                File.Copy(src, dst, true);
            }
        }

        WriteProject(CommonDir, ProjectName(CommonName), [_runtimeProject!],
            Directory.Exists(patches) ? [Path.Combine(patches, "**", "*.cs")] : []);

        var entryRefs = new List<string> { _runtimeProject!, Path.Combine(CommonDir, $"{ProjectName(CommonName)}.csproj") };
        entryRefs.AddRange(_images.Order().Select(i => Path.Combine(_outDir, i, $"{ProjectName(i)}.csproj")));
        WriteProject(EntryDir, ProjectName(EntryName), entryRefs, []);

        //an image folder left over from an earlier config would be picked up by the port's wildcard reference
        foreach (var dir in Directory.GetDirectories(_outDir))
        {
            var name = Path.GetFileName(dir);
            if (name == CommonName || name == EntryName || _images.Contains(name)) continue;
            if (File.Exists(Path.Combine(dir, $"{ProjectName(name)}.csproj"))) Directory.Delete(dir, true);
        }
    }

    private void WriteProject(string dir, string name, List<string> references, List<string> extraSources)
    {
        if (_runtimeProject == null) return;
        var sb = new StringBuilder();
        sb.AppendLine("<!-- generated by RecompOne.Recompiler (splitProjects), do not edit -->");
        sb.AppendLine("<Project Sdk=\"Microsoft.NET.Sdk\">");
        sb.AppendLine("  <PropertyGroup>");
        sb.AppendLine("    <TargetFramework>net10.0</TargetFramework>");
        sb.AppendLine("    <ImplicitUsings>enable</ImplicitUsings>");
        sb.AppendLine("    <Nullable>disable</Nullable>");
        sb.AppendLine($"    <AssemblyName>{name}</AssemblyName>");
        sb.AppendLine("    <RootNamespace>Recompiled</RootNamespace>");
        sb.AppendLine("  </PropertyGroup>");
        sb.AppendLine("  <ItemGroup>");
        foreach (var r in references)
            sb.AppendLine($"    <ProjectReference Include=\"{Path.GetRelativePath(dir, r)}\" />");
        foreach (var src in extraSources)
            sb.AppendLine($"    <Compile Include=\"{Path.GetRelativePath(dir, src)}\" />");
        sb.AppendLine("  </ItemGroup>");
        sb.AppendLine("</Project>");
        File.WriteAllText(Path.Combine(dir, $"{name}.csproj"), sb.ToString());
    }
}
