name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: build the runtime
        run: dotnet build RecompOne.Runtime/RecompOne.Runtime.csproj -c Release
      - name: build the recompiler
        run: dotnet build RecompOne.Recompiler -c Release
